/**
 * The canonical icon vocabulary: one entry per icon the app renders, naming the
 * equivalent glyph in each of the four supported libraries.
 *
 * This is the single source of truth. `scripts/generate-icon-registry.mjs` reads
 * it to emit the static-import registries in this directory, and `icons.tsx`
 * derives its public exports from it, so an icon is added in exactly one place.
 *
 * Extracted from the 242 `names={{ p, l, t, h }}` literals that used to sit inline
 * in icons.tsx, interleaved with 242 hand-written forwardRef wrappers.
 *
 * Fields:
 *   p — @phosphor-icons/react
 *   l — lucide-react
 *   t — @tabler/icons-react
 *   h — hugeicons-react
 *
 * A name that does not exist in a library is fine: the generator reports it, and
 * that library falls back to the default set for that one glyph.
 */

export interface IconNameMap {
  /** @phosphor-icons/react */
  p: string;
  /** lucide-react */
  l: string;
  /** @tabler/icons-react */
  t: string;
  /** hugeicons-react */
  h: string;
}

export const ICON_NAMES = {
  ALargeSmall: { p: "TextAa", l: "ALargeSmall", t: "IconALargeSmall", h: "InputTextIcon" },
  Activity: { p: "Pulse", l: "Activity", t: "IconActivity", h: "Activity01Icon" },
  AlertCircle: { p: "WarningCircle", l: "AlertCircle", t: "IconAlertCircle", h: "Alert01Icon" },
  AlertTriangle: { p: "Warning", l: "AlertTriangle", t: "IconAlertTriangle", h: "Alert02Icon" },
  Apple: { p: "AppleLogo", l: "Apple", t: "IconApple", h: "AppleIcon" },
  Archive: { p: "Archive", l: "Archive", t: "IconArchive", h: "Archive02Icon" },
  ArchiveRestore: { p: "Archive", l: "ArchiveRestore", t: "IconArchiveRestore", h: "Archive01Icon" },
  ArrowDown: { p: "ArrowDown", l: "ArrowDown", t: "IconArrowDown", h: "ArrowDown02Icon" },
  ArrowDownAZ: { p: "SortAscending", l: "ArrowDownAZ", t: "IconArrowDownAZ", h: "SortByDown01Icon" },
  ArrowDownNarrowWide: { p: "SortAscending", l: "ArrowDownNarrowWide", t: "IconArrowDownNarrowWide", h: "SortByDown02Icon" },
  ArrowDownWideNarrow: { p: "SortDescending", l: "ArrowDownWideNarrow", t: "IconArrowDownWideNarrow", h: "SortByDown01Icon" },
  ArrowLeft: { p: "ArrowLeft", l: "ArrowLeft", t: "IconArrowLeft", h: "ArrowLeft02Icon" },
  ArrowLeftRight: { p: "ArrowsLeftRight", l: "ArrowLeftRight", t: "IconArrowsLeftRight", h: "ArrowLeftRightIcon" },
  ArrowRight: { p: "ArrowRight", l: "ArrowRight", t: "IconArrowRight", h: "ArrowRight02Icon" },
  ArrowUp: { p: "ArrowUp", l: "ArrowUp", t: "IconArrowUp", h: "ArrowUp02Icon" },
  ArrowUpNarrowWide: { p: "SortAscending", l: "ArrowUpNarrowWide", t: "IconArrowUpNarrowWide", h: "SortByUp02Icon" },
  ArrowUpSquare: { p: "ArrowSquareUp", l: "ArrowUpSquare", t: "IconSquareArrowUp", h: "SquareArrowUp01Icon" },
  ArrowUpWideNarrow: { p: "SortDescending", l: "ArrowUpWideNarrow", t: "IconArrowUpWideNarrow", h: "SortByUp01Icon" },
  Award: { p: "Medal", l: "Award", t: "IconAward", h: "Award02Icon" },
  BarChart3: { p: "ChartBar", l: "BarChart3", t: "IconBarChart3", h: "BarChartIcon" },
  Battery: { p: "BatteryMedium", l: "Battery", t: "IconBattery", h: "BatteryMedium02Icon" },
  Bean: { p: "BowlSteam", l: "Bean", t: "IconBowlSpoon", h: "CoffeeBeansIcon" },
  BedDouble: { p: "Bed", l: "BedDouble", t: "IconBedDouble", h: "BedDoubleIcon" },
  Beef: { p: "Cow", l: "Beef", t: "IconMeat", h: "SteakIcon" },
  Bell: { p: "Bell", l: "Bell", t: "IconBell", h: "Notification02Icon" },
  BellOff: { p: "BellSlash", l: "BellOff", t: "IconBellOff", h: "NotificationOff02Icon" },
  BellRing: { p: "BellRinging", l: "BellRing", t: "IconBellRing", h: "Notification03Icon" },
  Binoculars: { p: "Binoculars", l: "Binoculars", t: "IconBinoculars", h: "BinocularsIcon" },
  Bold: { p: "TextB", l: "Bold", t: "IconBold", h: "TextBoldIcon" },
  BookMarked: { p: "BookBookmark", l: "BookMarked", t: "IconBookMarked", h: "BookBookmark01Icon" },
  BookOpen: { p: "BookOpen", l: "BookOpen", t: "IconBookOpen", h: "BookOpen01Icon" },
  Bookmark: { p: "BookmarkSimple", l: "Bookmark", t: "IconBookmark", h: "AllBookmarkIcon" },
  BookmarkCheck: { p: "BookmarkSimple", l: "BookmarkCheck", t: "IconBookmarkCheck", h: "BookmarkCheck01Icon" },
  Bot: { p: "Robot", l: "Bot", t: "IconBot", h: "BotIcon" },
  Brain: { p: "Brain", l: "Brain", t: "IconBrain", h: "BrainIcon" },
  Building: { p: "Buildings", l: "Building", t: "IconBuilding", h: "Building02Icon" },
  Bus: { p: "Bus", l: "Bus", t: "IconBus", h: "Bus02Icon" },
  Calculator: { p: "Calculator", l: "Calculator", t: "IconCalculator", h: "CalculatorIcon" },
  Calendar: { p: "Calendar", l: "Calendar", t: "IconCalendar", h: "Calendar01Icon" },
  CalendarDays: { p: "CalendarDots", l: "CalendarDays", t: "IconCalendarDays", h: "Calendar03Icon" },
  CalendarIcon: { p: "Calendar", l: "CalendarIcon", t: "IconCalendarIcon", h: "Calendar01Icon" },
  Camera: { p: "Camera", l: "Camera", t: "IconCamera", h: "Camera02Icon" },
  Car: { p: "Car", l: "Car", t: "IconCar", h: "Car02Icon" },
  Carrot: { p: "Carrot", l: "Carrot", t: "IconCarrot", h: "CarrotIcon" },
  Check: { p: "Check", l: "Check", t: "IconCheck", h: "Tick02Icon" },
  CheckCheck: { p: "Checks", l: "CheckCheck", t: "IconCheckCheck", h: "CheckmarkBadge01Icon" },
  CheckCircle: { p: "CheckCircle", l: "CheckCircle", t: "IconCheckCircle", h: "CheckmarkCircle01Icon" },
  CheckCircle2: { p: "CheckCircle", l: "CheckCircle2", t: "IconCheckCircle2", h: "CheckmarkCircle02Icon" },
  Cherry: { p: "Cherries", l: "Cherry", t: "IconCherry", h: "CherryIcon" },
  ChevronDown: { p: "CaretDown", l: "ChevronDown", t: "IconChevronDown", h: "ArrowDown01Icon" },
  ChevronLeft: { p: "CaretLeft", l: "ChevronLeft", t: "IconChevronLeft", h: "ArrowLeft01Icon" },
  ChevronRight: { p: "CaretRight", l: "ChevronRight", t: "IconChevronRight", h: "ArrowRight01Icon" },
  ChevronUp: { p: "CaretUp", l: "ChevronUp", t: "IconChevronUp", h: "ArrowUp01Icon" },
  ChevronsDown: { p: "CaretDoubleDown", l: "ChevronsDown", t: "IconChevronsDown", h: "ArrowDownDoubleIcon" },
  ChevronsUp: { p: "CaretDoubleUp", l: "ChevronsUp", t: "IconChevronsUp", h: "ArrowUpDoubleIcon" },
  Circle: { p: "Circle", l: "Circle", t: "IconCircle", h: "CircleIcon" },
  CircleCheck: { p: "CheckCircle", l: "CircleCheck", t: "IconCircleCheck", h: "CheckmarkCircle01Icon" },
  Citrus: { p: "Orange", l: "Citrus", t: "IconCitrus", h: "OrangeIcon" },
  Clipboard: { p: "Clipboard", l: "Clipboard", t: "IconClipboard", h: "ClipboardIcon" },
  ClipboardCopy: { p: "Clipboard", l: "ClipboardCopy", t: "IconClipboardCopy", h: "Copy01Icon" },
  Clock: { p: "Clock", l: "Clock", t: "IconClock", h: "Time02Icon" },
  Cloud: { p: "Cloud", l: "Cloud", t: "IconCloud", h: "CloudIcon" },
  CloudDrizzle: { p: "CloudRain", l: "CloudDrizzle", t: "IconCloudDrizzle", h: "CloudLittleRainIcon" },
  CloudFog: { p: "CloudFog", l: "CloudFog", t: "IconCloudFog", h: "CloudIcon" },
  CloudLightning: { p: "CloudLightning", l: "CloudLightning", t: "IconCloudLightning", h: "CloudAngledZapIcon" },
  CloudRain: { p: "CloudRain", l: "CloudRain", t: "IconCloudRain", h: "CloudBigRainIcon" },
  CloudSnow: { p: "CloudSnow", l: "CloudSnow", t: "IconCloudSnow", h: "CloudSnowIcon" },
  CloudSun: { p: "CloudSun", l: "CloudSun", t: "IconCloudSun", h: "SunCloud01Icon" },
  Cloudy: { p: "Cloud", l: "Cloudy", t: "IconCloudy", h: "CloudIcon" },
  Coffee: { p: "Coffee", l: "Coffee", t: "IconCoffee", h: "Coffee02Icon" },
  Compass: { p: "Compass", l: "Compass", t: "IconCompass", h: "Compass01Icon" },
  Contrast: { p: "CircleHalf", l: "Contrast", t: "IconContrast", h: "Image03Icon" },
  Cookie: { p: "Cookie", l: "Cookie", t: "IconCookie", h: "CookieIcon" },
  Copy: { p: "Copy", l: "Copy", t: "IconCopy", h: "Copy01Icon" },
  CornerDownLeft: { p: "ArrowElbowDownLeft", l: "CornerDownLeft", t: "IconCornerDownLeft", h: "ArrowTurnDownIcon" },
  Crosshair: { p: "Crosshair", l: "Crosshair", t: "IconCrosshair", h: "Target01Icon" },
  Crown: { p: "Crown", l: "Crown", t: "IconCrown", h: "CrownIcon" },
  CupSoda: { p: "PintGlass", l: "CupSoda", t: "IconCup", h: "DrinkIcon" },
  Database: { p: "Database", l: "Database", t: "IconDatabase", h: "DatabaseIcon" },
  Dices: { p: "DiceFive", l: "Dices", t: "IconDices", h: "DiceIcon" },
  DoorOpen: { p: "DoorOpen", l: "DoorOpen", t: "IconDoorOpen", h: "Door01Icon" },
  Download: { p: "DownloadSimple", l: "Download", t: "IconDownload", h: "Download01Icon" },
  Droplet: { p: "Drop", l: "Droplet", t: "IconDroplet", h: "DropletIcon" },
  Droplets: { p: "Drop", l: "Droplets", t: "IconDroplets", h: "DropletIcon" },
  Dumbbell: { p: "Barbell", l: "Dumbbell", t: "IconDumbbell", h: "Dumbbell01Icon" },
  Egg: { p: "Egg", l: "Egg", t: "IconEgg", h: "EggsIcon" },
  Eraser: { p: "Eraser", l: "Eraser", t: "IconEraser", h: "EraserIcon" },
  ExternalLink: { p: "ArrowSquareOut", l: "ExternalLink", t: "IconExternalLink", h: "LinkSquare01Icon" },
  Eye: { p: "Eye", l: "Eye", t: "IconEye", h: "ViewIcon" },
  EyeOff: { p: "EyeSlash", l: "EyeOff", t: "IconEyeOff", h: "ViewOffIcon" },
  Feather: { p: "Feather", l: "Feather", t: "IconFeather", h: "FeatherIcon" },
  FileText: { p: "FileText", l: "FileText", t: "IconFileText", h: "FileEditIcon" },
  Filter: { p: "Funnel", l: "Filter", t: "IconFilter", h: "FilterIcon" },
  Fish: { p: "Fish", l: "Fish", t: "IconFish", h: "FishFoodIcon" },
  Flag: { p: "Flag", l: "Flag", t: "IconFlag", h: "Flag02Icon" },
  Flame: { p: "Flame", l: "Flame", t: "IconFlame", h: "FireIcon" },
  FlaskConical: { p: "Flask", l: "FlaskConical", t: "IconFlaskConical", h: "TestTube01Icon" },
  FolderOpen: { p: "FolderOpen", l: "FolderOpen", t: "IconFolderOpen", h: "FolderOpenIcon" },
  Forward: { p: "ArrowBendUpRight", l: "Forward", t: "IconForward", h: "ArrowTurnForwardIcon" },
  Gamepad2: { p: "GameController", l: "Gamepad2", t: "IconGamepad2", h: "GameController02Icon" },
  Gauge: { p: "Gauge", l: "Gauge", t: "IconGauge", h: "DashboardSpeed01Icon" },
  Github: { p: "GithubLogo", l: "Github", t: "IconBrandGithub", h: "GithubIcon" },
  Globe: { p: "Globe", l: "Globe", t: "IconGlobe", h: "Globe02Icon" },
  Grid3X3: { p: "GridNine", l: "Grid3X3", t: "IconGrid3X3", h: "GridIcon" },
  HandHeart: { p: "HandHeart", l: "HandHeart", t: "IconHandHeart", h: "HandPrayerIcon" },
  HardDrive: { p: "HardDrive", l: "HardDrive", t: "IconHardDrive", h: "HardDriveIcon" },
  Hash: { p: "Hash", l: "Hash", t: "IconHash", h: "HashtagIcon" },
  Heart: { p: "Heart", l: "Heart", t: "IconHeart", h: "HeartAddIcon" },
  HelpCircle: { p: "Question", l: "HelpCircle", t: "IconHelpCircle", h: "QuestionIcon" },
  History: { p: "ClockCounterClockwise", l: "History", t: "IconHistory", h: "TransactionHistoryIcon" },
  Home: { p: "House", l: "Home", t: "IconHome", h: "Home03Icon" },
  House: { p: "House", l: "House", t: "IconHouse", h: "Home03Icon" },
  Image: { p: "Image", l: "Image", t: "IconImage", h: "Image01Icon" },
  ImageIcon: { p: "Image", l: "ImageIcon", t: "IconImageIcon", h: "Image01Icon" },
  ImageOff: { p: "ImageBroken", l: "ImageOff", t: "IconImageOff", h: "ImageNotFound01Icon" },
  ImagePlus: { p: "ImageSquare", l: "ImagePlus", t: "IconPhotoPlus", h: "ImageAdd01Icon" },
  Info: { p: "Info", l: "Info", t: "IconInfo", h: "CovidInfoIcon" },
  Key: { p: "Key", l: "Key", t: "IconKey", h: "Key01Icon" },
  Landmark: { p: "Bank", l: "Landmark", t: "IconLandmark", h: "BankIcon" },
  Languages: { p: "Translate", l: "Languages", t: "IconLanguages", h: "LanguageSkillIcon" },
  Layers: { p: "Stack", l: "Layers", t: "IconLayers", h: "LayerIcon" },
  Layout: { p: "Layout", l: "Layout", t: "IconLayout", h: "Layout01Icon" },
  LayoutGrid: { p: "SquaresFour", l: "LayoutGrid", t: "IconLayoutGrid", h: "LayoutGridIcon" },
  Leaf: { p: "Leaf", l: "Leaf", t: "IconLeaf", h: "Leaf02Icon" },
  Library: { p: "Books", l: "Library", t: "IconLibrary", h: "LibraryIcon" },
  LibraryBig: { p: "Books", l: "LibraryBig", t: "IconLibraryBig", h: "LibraryIcon" },
  Lightbulb: { p: "Lightbulb", l: "Lightbulb", t: "IconLightbulb", h: "BulbIcon" },
  Link2: { p: "Link", l: "Link2", t: "IconLink2", h: "Link04Icon" },
  List: { p: "List", l: "List", t: "IconList", h: "ListViewIcon" },
  ListMusic: { p: "MusicNotes", l: "ListMusic", t: "IconMusic", h: "Playlist02Icon" },
  ListPlus: { p: "ListPlus", l: "ListPlus", t: "IconListDetails", h: "TaskEdit02Icon" },
  Loader: { p: "SpinnerGap", l: "Loader", t: "IconLoader", h: "Loading01Icon" },
  Loader2: { p: "CircleNotch", l: "Loader2", t: "IconLoader2", h: "Loading03Icon" },
  Lock: { p: "Lock", l: "Lock", t: "IconLock", h: "LockIcon" },
  LogIn: { p: "SignIn", l: "LogIn", t: "IconLogIn", h: "Login02Icon" },
  LogOut: { p: "SignOut", l: "LogOut", t: "IconLogOut", h: "Logout02Icon" },
  Luggage: { p: "SuitcaseRolling", l: "Luggage", t: "IconLuggage", h: "Luggage01Icon" },
  Map: { p: "MapTrifold", l: "Map", t: "IconMap", h: "GoogleMapsIcon" },
  MapPin: { p: "MapPin", l: "MapPin", t: "IconMapPin", h: "MapPinpoint01Icon" },
  MapPinned: { p: "MapPinArea", l: "MapPinned", t: "IconMapPinFilled", h: "MapPinpoint01Icon" },
  Maximize2: { p: "ArrowsOut", l: "Maximize2", t: "IconMaximize2", h: "Maximize02Icon" },
  MessageCircle: { p: "ChatCircle", l: "MessageCircle", t: "IconMessageCircle", h: "BubbleChatIcon" },
  MessageSquare: { p: "ChatCentered", l: "MessageSquare", t: "IconMessage", h: "BubbleChatIcon" },
  MessageSquareText: { p: "ChatText", l: "MessageSquareText", t: "IconMessageSquareText", h: "BubbleChatIcon" },
  Mic: { p: "Microphone", l: "Mic", t: "IconMic", h: "Mic01Icon" },
  Milk: { p: "Cow", l: "Milk", t: "IconMilk", h: "MilkBottleIcon" },
  Minus: { p: "Minus", l: "Minus", t: "IconMinus", h: "MinusSignIcon" },
  Moon: { p: "Moon", l: "Moon", t: "IconMoon", h: "Moon02Icon" },
  MoonStar: { p: "MoonStars", l: "MoonStar", t: "IconMoonStar", h: "Moon02Icon" },
  MoreHorizontal: { p: "DotsThree", l: "MoreHorizontal", t: "IconMoreHorizontal", h: "MoreHorizontalCircle01Icon" },
  MoreVertical: { p: "DotsThreeVertical", l: "MoreVertical", t: "IconMoreVertical", h: "MoreVerticalCircle01Icon" },
  Mountain: { p: "Mountains", l: "Mountain", t: "IconMountain", h: "MountainIcon" },
  Music: { p: "MusicNotes", l: "Music", t: "IconMusic", h: "MusicNote03Icon" },
  Navigation: { p: "NavigationArrow", l: "Navigation", t: "IconNavigation", h: "Navigation01Icon" },
  Network: { p: "ShareNetwork", l: "Network", t: "IconNetwork", h: "AiNetworkIcon" },
  Newspaper: { p: "Newspaper", l: "Newspaper", t: "IconNewspaper", h: "News01Icon" },
  Nut: { p: "Nut", l: "Nut", t: "IconNut", h: "NutIcon" },
  Paintbrush: { p: "PaintBrush", l: "Paintbrush", t: "IconPaintbrush", h: "PaintBrush01Icon" },
  Palette: { p: "Palette", l: "Palette", t: "IconPalette", h: "PaintBoardIcon" },
  Pause: { p: "Pause", l: "Pause", t: "IconPause", h: "PauseCircleIcon" },
  PenLine: { p: "PencilSimpleLine", l: "PenLine", t: "IconPenLine", h: "Pen01Icon" },
  Pencil: { p: "PencilSimple", l: "Pencil", t: "IconPencil", h: "PencilEdit01Icon" },
  PiggyBank: { p: "PiggyBank", l: "PiggyBank", t: "IconPiggyBank", h: "PiggyBankIcon" },
  Pin: { p: "PushPin", l: "Pin", t: "IconPin", h: "PinIcon" },
  PinOff: { p: "PushPinSlash", l: "PinOff", t: "IconPinOff", h: "PinOffIcon" },
  Plane: { p: "Airplane", l: "Plane", t: "IconPlane", h: "Airplane02Icon" },
  Play: { p: "Play", l: "Play", t: "IconPlay", h: "PlayCircle02Icon" },
  Plus: { p: "Plus", l: "Plus", t: "IconPlus", h: "Add01Icon" },
  Puzzle: { p: "PuzzlePiece", l: "Puzzle", t: "IconPuzzle", h: "PuzzleIcon" },
  Quote: { p: "Quotes", l: "Quote", t: "IconQuote", h: "LeftToRightBlockQuoteIcon" },
  RefreshCcw: { p: "ArrowsCounterClockwise", l: "RefreshCcw", t: "IconRefreshCcw", h: "RefreshIcon" },
  RefreshCw: { p: "ArrowsClockwise", l: "RefreshCw", t: "IconRefreshCw", h: "Refresh01Icon" },
  Repeat: { p: "Repeat", l: "Repeat", t: "IconRepeat", h: "RepeatIcon" },
  Reply: { p: "ArrowBendUpLeft", l: "Reply", t: "IconReply", h: "MailReply01Icon" },
  RotateCcw: { p: "ArrowCounterClockwise", l: "RotateCcw", t: "IconRotateCcw", h: "ArrowTurnBackwardIcon" },
  RotateCw: { p: "ArrowClockwise", l: "RotateCw", t: "IconRotateCw", h: "ArrowTurnForwardIcon" },
  Route: { p: "Path", l: "Route", t: "IconRoute", h: "Route01Icon" },
  Rows3: { p: "Rows", l: "Rows3", t: "IconRows3", h: "AiBrowserIcon" },
  Rss: { p: "Rss", l: "Rss", t: "IconRss", h: "RssIcon" },
  Salad: { p: "BowlFood", l: "Salad", t: "IconSalad", h: "RiceBowl01Icon" },
  Save: { p: "FloppyDisk", l: "Save", t: "IconSave", h: "SaveEnergy01Icon" },
  Scale: { p: "Scales", l: "Scale", t: "IconScale", h: "BalanceScaleIcon" },
  ScrollText: { p: "Scroll", l: "ScrollText", t: "IconScrollText", h: "ScrollIcon" },
  Search: { p: "MagnifyingGlass", l: "Search", t: "IconSearch", h: "Search02Icon" },
  Send: { p: "PaperPlaneTilt", l: "Send", t: "IconSend", h: "SentIcon" },
  Settings: { p: "GearSix", l: "Settings", t: "IconSettings", h: "ComputerSettingsIcon" },
  Settings2: { p: "Gear", l: "Settings2", t: "IconSettings2", h: "Settings02Icon" },
  Share2: { p: "ShareNetwork", l: "Share2", t: "IconShare2", h: "Share01Icon" },
  Shield: { p: "Shield", l: "Shield", t: "IconShield", h: "Shield02Icon" },
  ShieldAlert: { p: "ShieldWarning", l: "ShieldAlert", t: "IconShieldAlert", h: "Shield01Icon" },
  ShieldCheck: { p: "ShieldCheck", l: "ShieldCheck", t: "IconShieldCheck", h: "ShieldUserIcon" },
  ShieldOff: { p: "ShieldSlash", l: "ShieldOff", t: "IconShieldOff", h: "Shield02Icon" },
  Shirt: { p: "TShirt", l: "Shirt", t: "IconShirt", h: "LongSleeveShirtIcon" },
  Shuffle: { p: "Shuffle", l: "Shuffle", t: "IconShuffle", h: "ShuffleIcon" },
  SlidersHorizontal: { p: "SlidersHorizontal", l: "SlidersHorizontal", t: "IconSlidersHorizontal", h: "SlidersHorizontalIcon" },
  Sliders: { p: "Sliders", l: "Sliders", t: "IconAdjustmentsHorizontal", h: "SlidersHorizontalIcon" },
  Smartphone: { p: "DeviceMobile", l: "Smartphone", t: "IconSmartphone", h: "SmartPhone01Icon" },
  Smile: { p: "Smiley", l: "Smile", t: "IconSmile", h: "SmileIcon" },
  Sparkle: { p: "Sparkle", l: "Sparkle", t: "IconSparkle", h: "SparklesIcon" },
  Sparkles: { p: "Sparkle", l: "Sparkles", t: "IconSparkles", h: "SparklesIcon" },
  Sprout: { p: "Plant", l: "Sprout", t: "IconSprout", h: "Plant02Icon" },
  Square: { p: "Square", l: "Square", t: "IconSquare", h: "SquareIcon" },
  Star: { p: "Star", l: "Star", t: "IconStar", h: "StarIcon" },
  Store: { p: "Storefront", l: "Store", t: "IconStore", h: "Store02Icon" },
  Sun: { p: "Sun", l: "Sun", t: "IconSun", h: "Sun01Icon" },
  SunDim: { p: "SunDim", l: "SunDim", t: "IconSunDim", h: "Sun02Icon" },
  Sunrise: { p: "SunHorizon", l: "Sunrise", t: "IconSunrise", h: "SunriseIcon" },
  Sunset: { p: "SunHorizon", l: "Sunset", t: "IconSunset", h: "SunsetIcon" },
  Swords: { p: "Sword", l: "Swords", t: "IconSwords", h: "Sword01Icon" },
  Target: { p: "Target", l: "Target", t: "IconTarget", h: "Target02Icon" },
  Thermometer: { p: "Thermometer", l: "Thermometer", t: "IconThermometer", h: "ThermometerIcon" },
  Timer: { p: "Timer", l: "Timer", t: "IconTimer", h: "Timer02Icon" },
  TimerOff: { p: "Timer", l: "TimerOff", t: "IconTimerOff", h: "Timer02Icon" },
  Trash: { p: "Trash", l: "Trash", t: "IconTrash", h: "Delete02Icon" },
  Trash2: { p: "TrashSimple", l: "Trash2", t: "IconTrash2", h: "Delete02Icon" },
  Trees: { p: "Tree", l: "Trees", t: "IconTrees", h: "Tree02Icon" },
  TrendingDown: { p: "TrendDown", l: "TrendingDown", t: "IconTrendingDown", h: "ChartDownIcon" },
  TrendingUp: { p: "TrendUp", l: "TrendingUp", t: "IconTrendingUp", h: "ChartUpIcon" },
  Trophy: { p: "Trophy", l: "Trophy", t: "IconTrophy", h: "Award01Icon" },
  Type: { p: "TextT", l: "Type", t: "IconType", h: "TextFontIcon" },
  Undo2: { p: "ArrowArcLeft", l: "Undo2", t: "IconUndo2", h: "UndoIcon" },
  Unlock: { p: "LockOpen", l: "Unlock", t: "IconUnlock", h: "BubbleChatUnlockIcon" },
  Upload: { p: "UploadSimple", l: "Upload", t: "IconUpload", h: "Upload01Icon" },
  User: { p: "User", l: "User", t: "IconUser", h: "UserIcon" },
  User2: { p: "User", l: "User2", t: "IconUser2", h: "UserIcon" },
  UserCircle: { p: "UserCircle", l: "UserCircle", t: "IconUserCircle", h: "UserCircleIcon" },
  UserMinus: { p: "UserMinus", l: "UserMinus", t: "IconUserMinus", h: "UserRemove01Icon" },
  UserPlus: { p: "UserPlus", l: "UserPlus", t: "IconUserPlus", h: "UserAdd01Icon" },
  Users: { p: "Users", l: "Users", t: "IconUsers", h: "UserMultiple02Icon" },
  Utensils: { p: "ForkKnife", l: "Utensils", t: "IconUtensils", h: "RestaurantIcon" },
  UtensilsCrossed: { p: "ForkKnife", l: "UtensilsCrossed", t: "IconUtensilsCrossed", h: "RestaurantIcon" },
  Vibrate: { p: "Vibrate", l: "Vibrate", t: "IconVibrate", h: "SmartPhone01Icon" },
  Video: { p: "VideoCamera", l: "Video", t: "IconVideo", h: "Video02Icon" },
  Volume2: { p: "SpeakerHigh", l: "Volume2", t: "IconVolume2", h: "VolumeHighIcon" },
  VolumeX: { p: "SpeakerSlash", l: "VolumeX", t: "IconVolumeX", h: "VolumeMute02Icon" },
  Waves: { p: "Waves", l: "Waves", t: "IconWaves", h: "WaveSquareIcon" },
  Wheat: { p: "Grains", l: "Wheat", t: "IconWheat", h: "Bread01Icon" },
  Wifi: { p: "WifiHigh", l: "Wifi", t: "IconWifi", h: "Wifi01Icon" },
  WifiOff: { p: "WifiSlash", l: "WifiOff", t: "IconWifiOff", h: "WifiDisconnected02Icon" },
  Wind: { p: "Wind", l: "Wind", t: "IconWind", h: "CloudFastWindIcon" },
  Wrench: { p: "Wrench", l: "Wrench", t: "IconWrench", h: "Wrench01Icon" },
  X: { p: "X", l: "X", t: "IconX", h: "Cancel01Icon" },
  Zap: { p: "Lightning", l: "Zap", t: "IconZap", h: "ZapIcon" },
  ZoomIn: { p: "MagnifyingGlassPlus", l: "ZoomIn", t: "IconZoomIn", h: "ZoomInAreaIcon" },
  ZoomOut: { p: "MagnifyingGlassMinus", l: "ZoomOut", t: "IconZoomOut", h: "ZoomOutAreaIcon" },
} as const satisfies Record<string, IconNameMap>;

/** Every icon name this module exports. */
export type IconName = keyof typeof ICON_NAMES;

export const ICON_NAME_LIST = Object.keys(ICON_NAMES) as readonly IconName[];

/**
 * Tabler uses a more opinionated naming system than Lucide, so neither a direct
 * translation nor the word-swap heuristic finds these. Curated by hand so a user
 * who picks "tabler" genuinely gets tabler glyphs instead of a silent fallback.
 */
export const TABLER_NAME_FALLBACKS: Partial<Record<string, readonly string[]>> = {
  ALargeSmall: ['IconTextSize'],
  BookMarked: ['IconBookmarkFilled'],
  BookOpen: ['IconBook'],
  BookmarkCheck: ['IconBookmarkPlus'],
  CalendarDays: ['IconCalendarDot'],
  CheckCircle2: ['IconCircleCheck'],
  Citrus: ['IconLemon2'],
  CloudLightning: ['IconCloudBolt'],
  CloudSun: ['IconCloud'],
  Dices: ['IconDice5'],
  DoorOpen: ['IconDoorEnter'],
  Forward: ['IconArrowForward'],
  Gamepad2: ['IconDeviceGamepad2'],
  Grid3X3: ['IconGrid3x3'],
  HandHeart: ['IconHeartHandshake'],
  HardDrive: ['IconDeviceSdCard'],
  House: ['IconHome2'],
  Image: ['IconPhoto'],
  ImageIcon: ['IconPhoto'],
  ImageOff: ['IconPhotoOff'],
  Info: ['IconInfoCircle'],
  Landmark: ['IconBuildingBank'],
  Languages: ['IconLanguage'],
  Lightbulb: ['IconBulb'],
  LogIn: ['IconLogin'],
  LogOut: ['IconLogout'],
  Maximize2: ['IconArrowsMaximize'],
  MessageSquareText: ['IconMessage2'],
  MoreHorizontal: ['IconDots'],
  MoreVertical: ['IconDotsVertical'],
  Newspaper: ['IconNews'],
  Paintbrush: ['IconBrush'],
  Pause: ['IconPlayerPause'],
  PenLine: ['IconPencil'],
  PiggyBank: ['IconPigMoney'],
  PinOff: ['IconPinnedOff'],
  Play: ['IconPlayerPlay'],
  RefreshCcw: ['IconRefresh'],
  RefreshCw: ['IconRefresh'],
  Reply: ['IconArrowBackUp'],
  RotateCcw: ['IconRotate'],
  RotateCw: ['IconRotateClockwise'],
  Rows3: ['IconLayoutRows'],
  Save: ['IconDeviceFloppy'],
  ScrollText: ['IconFileText'],
  ShieldAlert: ['IconShieldExclamation'],
  Shuffle: ['IconArrowsShuffle'],
  SlidersHorizontal: ['IconAdjustmentsHorizontal'],
  Smile: ['IconMoodSmile'],
  Store: ['IconBuildingStore'],
  SunDim: ['IconSunLow'],
  Timer: ['IconStopwatch'],
  TimerOff: ['IconClockOff'],
  Trash2: ['IconTrash'],
  Type: ['IconTypography'],
  Undo2: ['IconArrowBackUp'],
  Utensils: ['IconToolsKitchen2'],
  UtensilsCrossed: ['IconToolsKitchen2'],
  Vibrate: ['IconDeviceMobileVibration'],
  VolumeX: ['IconVolumeOff'],
  Waves: ['IconRipple'],
  Wrench: ['IconTool'],
  Zap: ['IconBolt'],
};
