// Body Systems Atlas — maps body systems to Atlas elements & their precise actions
// Bilingual (Arabic / German). Used by SkinHair (الجسد) tab.

export interface BodyEffect {
  name: { ar: string; de: string };
  action: { ar: string; de: string };
}

export interface BodySystem {
  key: string;
  icon: string; // emoji-free icon name from lucide
  title: { ar: string; de: string };
  summary: { ar: string; de: string };
  effects: BodyEffect[];
}

export const bodySystems: BodySystem[] = [
  {
    key: 'skin',
    icon: 'Droplets',
    title: { ar: 'البشرة', de: 'Haut' },
    summary: {
      ar: 'حاجز الكولاجين والإيلاستين، الترطيب من الداخل، حماية من الأكسدة والضوء الأزرق.',
      de: 'Kollagen-Elastin-Barriere, innere Hydration, Schutz vor Oxidation und Blaulicht.',
    },
    effects: [
      { name: { ar: 'الكولاجين المتحلل (Type I & III)', de: 'Hydrolysiertes Kollagen (Typ I & III)' },
        action: { ar: 'يحفّز الخلايا الليفية لإنتاج كولاجين داخلي ويرفع كثافة الأدمة خلال 8–12 أسبوعاً.', de: 'Stimuliert Fibroblasten und erhöht die Dermisdichte in 8–12 Wochen.' } },
      { name: { ar: 'فيتامين C (أسكوربات)', de: 'Vitamin C (Ascorbat)' },
        action: { ar: 'مرافق إلزامي لإنزيمات هيدروكسلة البرولين — بدونه لا يُبنى كولاجين مستقر.', de: 'Essenzieller Cofaktor für Prolyl-Hydroxylasen — ohne ihn kein stabiles Kollagen.' } },
      { name: { ar: 'الزنك + النحاس (2:1)', de: 'Zink + Kupfer (2:1)' },
        action: { ar: 'الزنك يُسرّع التئام الجروح والسيطرة على حب الشباب؛ النحاس يفعّل إنزيم اللايسيل أوكسيديز لتشابك الإيلاستين.', de: 'Zink für Wundheilung & Akne-Kontrolle; Kupfer aktiviert Lysyl-Oxidase für Elastin.' } },
      { name: { ar: 'الأستاكسانثين', de: 'Astaxanthin' },
        action: { ar: 'كاروتينويد يخترق الطبقة الدهنية ويخفّض الـ MMP-1 المسؤول عن تحلل الكولاجين بالأشعة فوق البنفسجية.', de: 'Carotinoid, das MMP-1 senkt und Kollagenabbau durch UV reduziert.' } },
      { name: { ar: 'حمض الهيالورونيك (وزن منخفض)', de: 'Hyaluronsäure (niedermolekular)' },
        action: { ar: 'يربط 1000× وزنه ماءً في الأدمة ويحفّز CD44 لتجديد البشرة.', de: 'Bindet das 1000-Fache seines Gewichts an Wasser, aktiviert CD44.' } },
      { name: { ar: 'البيوتين + النياسين', de: 'Biotin + Niacin' },
        action: { ar: 'مرافقات لتركيب الأحماض الدهنية في الطبقة القرنية للحفاظ على حاجز الجلد.', de: 'Cofaktoren der Fettsäuresynthese in der Hornschicht.' } },
      { name: { ar: 'أوميغا-3 (EPA/DHA)', de: 'Omega-3 (EPA/DHA)' },
        action: { ar: 'يُحوَّل إلى ريزولفينات تُطفئ التهاب الجلد المزمن (إكزيما، حب الشباب الالتهابي).', de: 'Wird in Resolvine umgewandelt, beendet chronische Hautentzündung.' } },
    ],
  },
  {
    key: 'hair',
    icon: 'Sparkles',
    title: { ar: 'الشعر والأظافر', de: 'Haar & Nägel' },
    summary: {
      ar: 'تكوين الكيراتين، طور النمو (Anagen)، تروية بصيلات فروة الرأس.',
      de: 'Keratinbildung, Anagen-Phase, Durchblutung der Follikel.',
    },
    effects: [
      { name: { ar: 'حديد الفيريتين (>70 ng/mL)', de: 'Ferritin-Eisen (>70 ng/mL)' },
        action: { ar: 'بدون مخزون كافٍ تنتقل البصيلات مبكراً إلى طور التساقط (Telogen Effluvium).', de: 'Niedriger Speicher → vorzeitiges Telogen Effluvium.' } },
      { name: { ar: 'البيوتين + L-سيستئين + MSM', de: 'Biotin + L-Cystein + MSM' },
        action: { ar: 'ثلاثي الكيراتين: المادة الأولية (سيستئين)، الإنزيم (بيوتين)، الكبريت العضوي (MSM) لروابط الديسلفيد.', de: 'Keratin-Trio: Baustein, Enzym-Cofaktor, organischer Schwefel für Disulfidbrücken.' } },
      { name: { ar: 'الزنك + السيلينيوم', de: 'Zink + Selen' },
        action: { ar: 'يثبّتان غدة الدرقية ويمنعان تساقط الشعر المرتبط بنقصها.', de: 'Stabilisieren die Schilddrüse, verhindern Haarausfall.' } },
      { name: { ar: 'سو بالميتو + بذور اليقطين', de: 'Sägepalme + Kürbiskerne' },
        action: { ar: 'تُبطّئ تحويل التستوستيرون إلى DHT المسبّب لحاصة الذكورة.', de: 'Hemmen die Umwandlung zu DHT (androgenetische Alopezie).' } },
      { name: { ar: 'فيتامين D3', de: 'Vitamin D3' },
        action: { ar: 'يفعّل مستقبلات VDR في بصيلات الشعر وضروري لدخول طور النمو.', de: 'Aktiviert VDR-Rezeptoren der Haarfollikel.' } },
    ],
  },
  {
    key: 'eyes',
    icon: 'Eye',
    title: { ar: 'العيون والرؤية', de: 'Augen & Sehkraft' },
    summary: {
      ar: 'حماية الشبكية من الضوء الأزرق، صحة البقعة الصفراء، رطوبة العين.',
      de: 'Netzhautschutz vor Blaulicht, Makula-Gesundheit, Tränenfilm.',
    },
    effects: [
      { name: { ar: 'لوتين + زياكسانثين', de: 'Lutein + Zeaxanthin' },
        action: { ar: 'يتراكمان حصراً في البقعة الصفراء ويرشّحان الضوء الأزرق عالي الطاقة (HEV).', de: 'Akkumulieren in der Makula, filtern HEV-Blaulicht.' } },
      { name: { ar: 'فيتامين A (ريتينول)', de: 'Vitamin A (Retinol)' },
        action: { ar: 'مكوّن جزيء الرودوبسين الضروري للرؤية في الإضاءة المنخفضة.', de: 'Bestandteil von Rhodopsin, essenziell für Nachtsehen.' } },
      { name: { ar: 'أستاكسانثين', de: 'Astaxanthin' },
        action: { ar: 'يعبر حاجز الدم/الشبكية ويُحسّن تدفق الدم في الشعيرات الدقيقة للعين.', de: 'Passiert Blut-Retina-Schranke, verbessert Mikrozirkulation.' } },
      { name: { ar: 'أوميغا-3 (DHA)', de: 'Omega-3 (DHA)' },
        action: { ar: 'يشكّل 60% من دهون الشبكية ويُخفّف جفاف العين.', de: '60% der Netzhaut-Lipide, lindert trockene Augen.' } },
    ],
  },
  {
    key: 'bones',
    icon: 'Bone',
    title: { ar: 'العظام والمفاصل', de: 'Knochen & Gelenke' },
    summary: {
      ar: 'كثافة العظم، الغضروف، مرونة المفاصل، السائل الزليلي.',
      de: 'Knochendichte, Knorpel, Gelenkbeweglichkeit, Synovialflüssigkeit.',
    },
    effects: [
      { name: { ar: 'فيتامين D3 + K2 (MK-7)', de: 'Vitamin D3 + K2 (MK-7)' },
        action: { ar: 'D3 يمتص الكالسيوم؛ K2 يُفعّل أوستيوكالسين فيوجّهه إلى العظم لا الشرايين.', de: 'D3 absorbiert Calcium; K2 aktiviert Osteocalcin, lenkt es zum Knochen.' } },
      { name: { ar: 'المغنيسيوم (Glycinate/Malate)', de: 'Magnesium (Glycinat/Malat)' },
        action: { ar: '60% من المغنيسيوم في العظم؛ يفعّل أكثر من 300 إنزيم لتجديد المصفوفة العظمية.', de: '60% in den Knochen; aktiviert >300 Enzyme der Knochenmatrix.' } },
      { name: { ar: 'البورون (Boron)', de: 'Bor' },
        action: { ar: 'يقلّل فقدان الكالسيوم البولي ويرفع التستوستيرون الحر.', de: 'Reduziert Calciumverlust im Urin, erhöht freies Testosteron.' } },
      { name: { ar: 'كولاجين Type II + UC-II', de: 'Kollagen Typ II + UC-II' },
        action: { ar: 'يُعيد بناء الغضروف ويقلّل آلام التهاب المفاصل بآلية المناعة الفموية.', de: 'Baut Knorpel auf, mindert Arthritis-Schmerz via orale Toleranz.' } },
      { name: { ar: 'MSM + جلوكوزامين + كوندرويتين', de: 'MSM + Glucosamin + Chondroitin' },
        action: { ar: 'ثلاثي السائل الزليلي: يُحسّن التشحيم ومرونة المفصل خلال 6–8 أسابيع.', de: 'Trio für Synovialflüssigkeit: 6–8 Wochen bis zur Verbesserung.' } },
      { name: { ar: 'السيليكا (من الذيل الحصان)', de: 'Silizium (Schachtelhalm)' },
        action: { ar: 'يُحفّز الخلايا البانية للعظم ويربط الكولاجين بالكالسيوم.', de: 'Stimuliert Osteoblasten, vernetzt Kollagen mit Calcium.' } },
    ],
  },
  {
    key: 'muscles',
    icon: 'Dumbbell',
    title: { ar: 'العضلات والأداء', de: 'Muskeln & Leistung' },
    summary: {
      ar: 'تخليق البروتين، استشفاء، طاقة العضلة، حماية من الهدم.',
      de: 'Proteinsynthese, Regeneration, Muskelenergie, Antikatabolismus.',
    },
    effects: [
      { name: { ar: 'كرياتين مونوهيدرات', de: 'Kreatin-Monohydrat' },
        action: { ar: 'يرفع مخزون الفوسفوكرياتين 20%، يزيد القوة والكتلة العضلية والوظيفة المعرفية.', de: '+20% Phosphokreatin, mehr Kraft, Muskelmasse, kognitive Leistung.' } },
      { name: { ar: 'BCAA + L-ليوسين', de: 'BCAA + L-Leucin' },
        action: { ar: 'يُفعّل مسار mTOR لتخليق البروتين العضلي بعد التمرين.', de: 'Aktiviert mTOR-Signalweg für Muskelproteinsynthese.' } },
      { name: { ar: 'كرياتين + بيتا-ألانين', de: 'Kreatin + Beta-Alanin' },
        action: { ar: 'بيتا-ألانين يرفع الكارنوزين العضلي ويؤجّل الإرهاق في التمارين عالية الشدة.', de: 'Beta-Alanin erhöht Carnosin, verzögert Ermüdung.' } },
      { name: { ar: 'مغنيسيوم مالات', de: 'Magnesium-Malat' },
        action: { ar: 'يُقلّل آلام العضلات والتشنجات، ضروري لدورة كريبس.', de: 'Reduziert Muskelschmerz/Krämpfe, essenziell für Krebs-Zyklus.' } },
      { name: { ar: 'L-سيترولين', de: 'L-Citrullin' },
        action: { ar: 'يرفع أكسيد النيتريك ويحسن ضخ الدم للعضلة وأداء التحمل.', de: 'Erhöht NO, verbessert Muskelpump und Ausdauer.' } },
    ],
  },
  {
    key: 'mitochondria',
    icon: 'Battery',
    title: { ar: 'الميتوكوندريا والطاقة الخلوية', de: 'Mitochondrien & Zellenergie' },
    summary: {
      ar: 'مصانع ATP، الطاقة العميقة، الإحماء الخلوي، حماية الجذور الحرة.',
      de: 'ATP-Fabriken, tiefe Energie, Zellschutz vor freien Radikalen.',
    },
    effects: [
      { name: { ar: 'CoQ10 (Ubiquinol)', de: 'CoQ10 (Ubiquinol)' },
        action: { ar: 'المركّب رقم 10 في سلسلة نقل الإلكترون — بدونه لا يُنتج ATP.', de: 'Komplex 10 der Atmungskette — ohne ihn kein ATP.' } },
      { name: { ar: 'PQQ', de: 'PQQ' },
        action: { ar: 'الجزيء الوحيد المعروف الذي يحفّز تكوّن ميتوكوندريا جديدة (Biogenesis).', de: 'Einziges Molekül, das mitochondriale Biogenese auslöst.' } },
      { name: { ar: 'NMN / NR', de: 'NMN / NR' },
        action: { ar: 'سلائف NAD+ — يرفع وقود السرتوينات وإصلاح الـ DNA.', de: 'NAD+-Vorstufe, treibt Sirtuine und DNA-Reparatur an.' } },
      { name: { ar: 'L-كارنيتين (ALCAR)', de: 'L-Carnitin (ALCAR)' },
        action: { ar: 'يُدخل الأحماض الدهنية إلى الميتوكوندريا لحرقها كطاقة.', de: 'Transportiert Fettsäuren in die Mitochondrien.' } },
      { name: { ar: 'حمض ألفا ليبويك (R-ALA)', de: 'Alpha-Liponsäure (R-ALA)' },
        action: { ar: 'مضاد أكسدة شامل (دهني ومائي)، يُجدّد فيتامين C وE والجلوتاثيون.', de: 'Universelles Antioxidans, regeneriert Vit C, E, Glutathion.' } },
    ],
  },
  {
    key: 'brain',
    icon: 'Brain',
    title: { ar: 'الدماغ والإدراك', de: 'Gehirn & Kognition' },
    summary: {
      ar: 'النواقل العصبية، التركيز، الذاكرة، حماية الخلايا العصبية، النمو العصبي (BDNF/NGF).',
      de: 'Neurotransmitter, Fokus, Gedächtnis, Neuroprotektion, BDNF/NGF.',
    },
    effects: [
      { name: { ar: 'أوميغا-3 (DHA)', de: 'Omega-3 (DHA)' },
        action: { ar: '40% من دهون المخ — يحافظ على مرونة الغشاء العصبي وانتقال الإشارات.', de: '40% der Hirnlipide — Membranfluidität, Synapsenleitung.' } },
      { name: { ar: 'Lion\'s Mane (هيريسينون/إيرينازين)', de: 'Lion\'s Mane (Hericenone/Erinacine)' },
        action: { ar: 'يحفّز عامل نمو الأعصاب NGF لإعادة بناء الخلايا العصبية.', de: 'Stimuliert NGF (Nerve Growth Factor).' } },
      { name: { ar: 'الباكوبا (Bacopa)', de: 'Bacopa monnieri' },
        action: { ar: 'يُحسّن سرعة معالجة الذاكرة طويلة الأمد عبر مستقبلات السيروتونين.', de: 'Verbessert Langzeitgedächtnis via 5-HT-Rezeptoren.' } },
      { name: { ar: 'L-ثيانين + كافيين', de: 'L-Theanin + Koffein' },
        action: { ar: 'يرفع موجات ألفا الدماغية ويعطي تركيزاً هادئاً بلا اهتزاز.', de: 'Erhöht Alpha-Wellen, ruhiger Fokus ohne Jitter.' } },
      { name: { ar: 'فوسفاتيديل سيرين (PS)', de: 'Phosphatidylserin (PS)' },
        action: { ar: 'يخفض الكورتيزول ويُحسن وظيفة الذاكرة في الإجهاد المزمن.', de: 'Senkt Cortisol, verbessert Gedächtnis bei Stress.' } },
      { name: { ar: 'B-Complex فعّال (ميثيل)', de: 'Aktiver B-Komplex (Methyl)' },
        action: { ar: 'الميثيل فولات + P5P + ميثيل B12 ضروريون لتركيب الدوبامين والسيروتونين.', de: 'Methylfolat + P5P + Methyl-B12 für Dopamin/Serotonin.' } },
    ],
  },
  {
    key: 'gut',
    icon: 'Sprout',
    title: { ar: 'الأمعاء والميكروبيوم', de: 'Darm & Mikrobiom' },
    summary: {
      ar: 'محور الأمعاء/الدماغ، حاجز الأمعاء، تنوع البكتيريا النافعة، إنتاج SCFA.',
      de: 'Darm-Hirn-Achse, Darmbarriere, Mikrobiom-Diversität, SCFA.',
    },
    effects: [
      { name: { ar: 'L-جلوتامين', de: 'L-Glutamin' },
        action: { ar: 'الوقود الأول لخلايا الأمعاء (Enterocytes) ويُصلح متلازمة الأمعاء المتسرّبة.', de: 'Primärer Brennstoff der Enterozyten, repariert Leaky Gut.' } },
      { name: { ar: 'Akkermansia muciniphila', de: 'Akkermansia muciniphila' },
        action: { ar: 'تُعزّز طبقة المخاط وتنظّم الحساسية للأنسولين والوزن.', de: 'Stärkt Mucinschicht, reguliert Insulinsensitivität.' } },
      { name: { ar: 'HMO (سكريات حليب الأم)', de: 'HMO (Humane Milcholigosaccharide)' },
        action: { ar: '2′-FL تعمل كطُعم مخادع لإزالة الممرضات وتغذية البيفيدوباكتيريا.', de: '2′-FL als Decoy-Rezeptor, füttert Bifidobakterien.' } },
      { name: { ar: 'L. rhamnosus GG + L. helveticus', de: 'L. rhamnosus GG + L. helveticus' },
        action: { ar: 'يرفعان GABA ويُخفّضان القلق عبر العصب المبهم (محور الأمعاء/الدماغ).', de: 'Erhöhen GABA, reduzieren Angst via Vagusnerv.' } },
      { name: { ar: 'البوتيرات (Butyrate)', de: 'Butyrat' },
        action: { ar: 'حمض دهني قصير السلسلة يُغذي القولون ويُهدّئ الالتهاب الجهازي.', de: 'Kurzkettige Fettsäure, nährt Kolon, beruhigt Entzündung.' } },
      { name: { ar: 'إنزيمات هضمية (Digezyme)', de: 'Verdauungsenzyme (Digezyme)' },
        action: { ar: 'أميليز/بروتيز/ليباز/سيلولاز/لاكتاز — تكسر الكربوهيدرات والبروتين والدهون.', de: 'Amylase/Protease/Lipase/Cellulase/Lactase.' } },
    ],
  },
  {
    key: 'immune',
    icon: 'Shield',
    title: { ar: 'المناعة', de: 'Immunsystem' },
    summary: {
      ar: 'كريات NK، الأجسام المضادة، الحاجز المخاطي، توازن Th1/Th2.',
      de: 'NK-Zellen, Antikörper, Schleimhautbarriere, Th1/Th2-Balance.',
    },
    effects: [
      { name: { ar: 'فيتامين D3', de: 'Vitamin D3' },
        action: { ar: 'يفعّل أكثر من 2000 جين مناعي، أهمها كاتيلسيدين المضاد للميكروبات.', de: 'Aktiviert >2000 Immungene, u. a. Cathelicidin.' } },
      { name: { ar: 'الزنك (Picolinate)', de: 'Zink (Picolinat)' },
        action: { ar: 'يمنع تكاثر الفيروسات داخل الخلية ويُحفّز خلايا T.', de: 'Hemmt virale Replikation, aktiviert T-Zellen.' } },
      { name: { ar: 'فيتامين C عالي الجرعة', de: 'Vitamin C (Hochdosis)' },
        action: { ar: 'يُحفّز كيموتاكسي العدلات ويُجدّد فيتامين E.', de: 'Aktiviert Neutrophilen-Chemotaxis, regeneriert Vit E.' } },
      { name: { ar: 'بيتا-جلوكان (1,3/1,6)', de: 'Beta-Glucan (1,3/1,6)' },
        action: { ar: 'يرتبط بمستقبلات Dectin-1 على البلاعم ويُدرّب المناعة الفطرية.', de: 'Bindet Dectin-1 auf Makrophagen, trainiert Immunsystem.' } },
      { name: { ar: 'الإلدربيري (Sambucus)', de: 'Holunder (Sambucus)' },
        action: { ar: 'يمنع التصاق فيروس الإنفلونزا بالخلايا ويُقصّر مدة المرض.', de: 'Hemmt Influenza-Adhäsion, verkürzt Krankheitsdauer.' } },
    ],
  },
  {
    key: 'heart',
    icon: 'Heart',
    title: { ar: 'القلب والدورة الدموية', de: 'Herz & Kreislauf' },
    summary: {
      ar: 'صحة الشرايين، أكسيد النيتريك، توازن الكوليسترول، ضغط الدم.',
      de: 'Arteriengesundheit, Stickstoffmonoxid, Lipidprofil, Blutdruck.',
    },
    effects: [
      { name: { ar: 'CoQ10', de: 'CoQ10' },
        action: { ar: 'القلب هو العضو الأكثر استهلاكاً للـ ATP — يدعمه مباشرة ويعوّض نقص الستاتينات.', de: 'Herz verbraucht am meisten ATP — CoQ10 essenziell, v. a. unter Statinen.' } },
      { name: { ar: 'أوميغا-3 (EPA)', de: 'Omega-3 (EPA)' },
        action: { ar: 'يُخفّض الثلاثيات الدهنية 30% ويُقلّل التهاب جدار الشريان.', de: 'Senkt Triglyceride um 30%, reduziert Arterienentzündung.' } },
      { name: { ar: 'فيتامين K2 (MK-7)', de: 'Vitamin K2 (MK-7)' },
        action: { ar: 'يفعّل MGP الذي يمنع تكلّس الشرايين.', de: 'Aktiviert MGP, verhindert Arterienverkalkung.' } },
      { name: { ar: 'L-أرجينين + L-سيترولين', de: 'L-Arginin + L-Citrullin' },
        action: { ar: 'سلائف أكسيد النيتريك (NO) لتوسيع الأوعية وتحسين الانتصاب.', de: 'NO-Vorstufen, gefäßerweiternd, verbessern Erektion.' } },
      { name: { ar: 'مغنيسيوم (Taurate)', de: 'Magnesium (Taurat)' },
        action: { ar: 'يُرخّي العضل الأملس للشرايين ويُخفّض ضغط الدم 5–10 mmHg.', de: 'Entspannt glatte Gefäßmuskulatur, senkt RR.' } },
    ],
  },
  {
    key: 'hormones',
    icon: 'Scale',
    title: { ar: 'الهرمونات والتوازن', de: 'Hormone & Balance' },
    summary: {
      ar: 'محور HPA، التستوستيرون، الإستروجين، الدرقية، الكورتيزول.',
      de: 'HPA-Achse, Testosteron, Östrogen, Schilddrüse, Cortisol.',
    },
    effects: [
      { name: { ar: 'الأشواغاندا (KSM-66)', de: 'Ashwagandha (KSM-66)' },
        action: { ar: 'مُكيّف للإجهاد، يُخفّض الكورتيزول 27% ويرفع التستوستيرون 15%.', de: 'Adaptogen, senkt Cortisol −27%, erhöht Testosteron +15%.' } },
      { name: { ar: 'DIM + I3C', de: 'DIM + I3C' },
        action: { ar: 'يوجّه استقلاب الإستروجين نحو 2-OH (الآمن) بعيداً عن 16-OH.', de: 'Lenkt Östrogenmetabolismus zu 2-OH (sicher).' } },
      { name: { ar: 'السيلينيوم + التيروسين', de: 'Selen + Tyrosin' },
        action: { ar: 'مادة بناء T4 وتفعيله إلى T3 الفعّال.', de: 'Bausteine für T4 und Aktivierung zu T3.' } },
      { name: { ar: 'الرهوديولا (Rhodiola)', de: 'Rhodiola rosea' },
        action: { ar: 'تُحسّن التحمل الذهني وتُنظّم محور HPA في الإجهاد المزمن.', de: 'Verbessert mentale Belastbarkeit, reguliert HPA-Achse.' } },
      { name: { ar: 'البورون (Boron)', de: 'Bor' },
        action: { ar: 'يرفع التستوستيرون الحر ويُخفّض SHBG.', de: 'Erhöht freies Testosteron, senkt SHBG.' } },
    ],
  },
  {
    key: 'methylation',
    icon: 'Dna',
    title: { ar: 'الميثلة والـ DNA', de: 'Methylierung & DNA' },
    summary: {
      ar: 'دورة المثيونين، إصلاح الـ DNA، إزالة الهوموسيستين، تنشيط الجينات.',
      de: 'Methionin-Zyklus, DNA-Reparatur, Homocystein-Abbau.',
    },
    effects: [
      { name: { ar: 'ميثيل فولات (5-MTHF)', de: 'Methylfolat (5-MTHF)' },
        action: { ar: 'الشكل الفعّال الوحيد للفولات الذي يعبر حاجز الدم/الدماغ.', de: 'Einzige aktive Form, die die Blut-Hirn-Schranke passiert.' } },
      { name: { ar: 'ميثيل B12 (Hydroxo/Methyl)', de: 'Methyl-B12 / Hydroxo-B12' },
        action: { ar: 'مرافق لإنزيم MTR لإعادة تدوير الهوموسيستين إلى مثيونين.', de: 'Cofaktor der MTR-Reaktion, recycelt Homocystein.' } },
      { name: { ar: 'TMG (تريميثيل جلايسين)', de: 'TMG (Trimethylglycin)' },
        action: { ar: 'مسار بديل (BHMT) لخفض الهوموسيستين عند طفرات MTHFR.', de: 'Alternativer BHMT-Weg bei MTHFR-Mutationen.' } },
      { name: { ar: 'P5P (B6 فعّال)', de: 'P5P (aktives B6)' },
        action: { ar: 'مرافق لـ CBS لتحويل الهوموسيستين إلى سيستئين وغلوتاثيون.', de: 'Cofaktor für CBS, leitet zu Cystein/Glutathion.' } },
    ],
  },
  {
    key: 'detox',
    icon: 'Droplet',
    title: { ar: 'الكبد وإزالة السموم', de: 'Leber & Entgiftung' },
    summary: {
      ar: 'الطورين الأول والثاني، الجلوتاثيون، ربط المعادن الثقيلة، تصريف القناة الصفراوية.',
      de: 'Phase I & II, Glutathion, Schwermetall-Bindung, Gallenfluss.',
    },
    effects: [
      { name: { ar: 'NAC (سيستئين)', de: 'NAC (Cystein)' },
        action: { ar: 'سلف الجلوتاثيون — السيد الأعلى لمضادات الأكسدة الداخلية.', de: 'Glutathion-Vorstufe, Meister-Antioxidans.' } },
      { name: { ar: 'سيليمارين (حليب الشوك)', de: 'Silymarin (Mariendistel)' },
        action: { ar: 'يحمي خلايا الكبد ويُجدّدها، يُنشّط RNA polymerase I.', de: 'Schützt und regeneriert Hepatozyten.' } },
      { name: { ar: 'الزيوليت (Clinoptilolite)', de: 'Zeolith (Klinoptilolith)' },
        action: { ar: 'هيكل بلوري دقيق يربط المعادن الثقيلة (رصاص، زئبق، كادميوم) ويُخرجها.', de: 'Bindet Schwermetalle (Pb, Hg, Cd) und scheidet sie aus.' } },
      { name: { ar: 'سلفورافان (براعم البروكلي)', de: 'Sulforaphan (Brokkolisprossen)' },
        action: { ar: 'يُحفّز Nrf2 ويرفع كل إنزيمات الطور الثاني للكبد.', de: 'Aktiviert Nrf2, hebt Phase-II-Enzyme.' } },
      { name: { ar: 'الكورستين + الكلوريلا', de: 'Quercetin + Chlorella' },
        action: { ar: 'الكورستين مضاد التهاب قوي؛ الكلوريلا تربط الزئبق في القناة الهضمية.', de: 'Quercetin entzündungshemmend; Chlorella bindet Quecksilber.' } },
    ],
  },
  {
    key: 'longevity',
    icon: 'Infinity',
    title: { ar: 'طول العمر والشيخوخة الخلوية', de: 'Longevity & Zellalterung' },
    summary: {
      ar: 'السرتوينات، الأوتوفاجي، التيلوميرات، إزالة الخلايا الهرمة (Senolytics).',
      de: 'Sirtuine, Autophagie, Telomere, Senolyse.',
    },
    effects: [
      { name: { ar: 'NMN + ريسفيراترول', de: 'NMN + Resveratrol' },
        action: { ar: 'NMN يرفع NAD+، الريسفيراترول يُفعّل SIRT1 — المحرّك الجيني للشباب الخلوي.', de: 'NMN → NAD+, Resveratrol → SIRT1 (Langlebigkeits-Gen).' } },
      { name: { ar: 'الفيزيتين (Fisetin)', de: 'Fisetin' },
        action: { ar: 'مادة سينولايتيك تُزيل الخلايا الزومبي (Senescent) المسبّبة للالتهاب المزمن.', de: 'Senolytikum, eliminiert seneszente "Zombie-Zellen".' } },
      { name: { ar: 'الإسبرميدين (Spermidine)', de: 'Spermidin' },
        action: { ar: 'يُحفّز الأوتوفاجي (إعادة تدوير الخلية) ويُحسّن مدة الحياة.', de: 'Induziert Autophagie, verlängert Lebensspanne.' } },
      { name: { ar: 'الكورستين', de: 'Quercetin' },
        action: { ar: 'سينولايتيك مساعد، يعمل مع الفيزيتين لتنظيف الخلايا الهرمة.', de: 'Senolytisches Adjuvans, synergiert mit Fisetin.' } },
      { name: { ar: 'الأرغو ثيوناين (Ergothioneine)', de: 'Ergothionein' },
        action: { ar: '"فيتامين طول العمر" — مضاد أكسدة يتراكم في الميتوكوندريا ويُبطّئ الشيخوخة.', de: '"Longevity-Vitamin", akkumuliert in Mitochondrien.' } },
    ],
  },
  {
    key: 'sleep',
    icon: 'Moon',
    title: { ar: 'النوم والإيقاع البيولوجي', de: 'Schlaf & Biorhythmus' },
    summary: {
      ar: 'الميلاتونين، GABA، النوم العميق، الساعة البيولوجية.',
      de: 'Melatonin, GABA, Tiefschlaf, zirkadianer Rhythmus.',
    },
    effects: [
      { name: { ar: 'مغنيسيوم (Glycinate)', de: 'Magnesium (Glycinat)' },
        action: { ar: 'الجلايسين يُهدّئ الجهاز العصبي ويُحسّن جودة النوم العميق.', de: 'Glycin beruhigt ZNS, vertieft Schlaf.' } },
      { name: { ar: 'L-ثيانين + GABA', de: 'L-Theanin + GABA' },
        action: { ar: 'يرفع موجات ألفا وثيتا ويُهدّئ الجهاز السمبثاوي.', de: 'Erhöht Alpha/Theta, beruhigt Sympathikus.' } },
      { name: { ar: 'ميلاتونين (جرعة منخفضة)', de: 'Melatonin (niedrig dosiert)' },
        action: { ar: '0.3–1 ملغ تُضبط الساعة البيولوجية بدون تثبيط الإفراز الذاتي.', de: '0,3–1 mg synchronisiert die innere Uhr.' } },
      { name: { ar: 'الأبيجينين (البابونج)', de: 'Apigenin (Kamille)' },
        action: { ar: 'يرتبط بمستقبلات البنزوديازيبين دون إدمان.', de: 'Bindet Benzodiazepin-Rezeptor ohne Suchtpotenzial.' } },
      { name: { ar: 'الجلايسين (3 غ قبل النوم)', de: 'Glycin (3 g vor dem Schlafen)' },
        action: { ar: 'يُخفّض حرارة الجسم الأساسية ويُسرّع الدخول للنوم العميق.', de: 'Senkt Kerntemperatur, beschleunigt Tiefschlaf.' } },
    ],
  },
  {
    key: 'mood',
    icon: 'Smile',
    title: { ar: 'المزاج والاتزان النفسي', de: 'Stimmung & psychisches Gleichgewicht' },
    summary: {
      ar: 'السيروتونين، الدوبامين، GABA، تقليل القلق والاكتئاب.',
      de: 'Serotonin, Dopamin, GABA, Anxiolyse, Antidepression.',
    },
    effects: [
      { name: { ar: 'سافرون (الزعفران)', de: 'Safran (Crocus sativus)' },
        action: { ar: '30 ملغ يومياً تُعادل مضادات اكتئاب SSRI خفيفة في الدراسات السريرية.', de: '30 mg/Tag wirksam wie milde SSRI in Studien.' } },
      { name: { ar: '5-HTP', de: '5-HTP' },
        action: { ar: 'السلف المباشر للسيروتونين — يعبر حاجز الدم/الدماغ مباشرة.', de: 'Direkte Serotonin-Vorstufe, passiert BHS.' } },
      { name: { ar: 'L-تايروسين', de: 'L-Tyrosin' },
        action: { ar: 'سلف الدوبامين والنورأدرينالين — يُحسّن الدافع والتركيز تحت الضغط.', de: 'Dopamin-/Noradrenalin-Vorstufe, fördert Antrieb.' } },
      { name: { ar: 'بروبيوتيكس نفسية (L. helveticus + B. longum)', de: 'Psychobiotika (L. helveticus + B. longum)' },
        action: { ar: 'تُخفّض القلق والاكتئاب عبر محور الأمعاء/الدماغ ورفع GABA.', de: 'Reduzieren Angst/Depression via Gut-Brain-Axis.' } },
    ],
  },
];
