// ─────────────────────────────────────────────────────────────────────────
// ESLint reports CORRECTNESS problems. Prettier owns FORMATTING.
//
// Running formatting through `eslint-plugin-prettier` made `bun run lint`
// print 22,098 quote-style complaints on top of ~1,800 real findings, so the
// gate was unusable and every genuine bug hid in the noise. Formatting is now
// checked separately with `bun run format:check` (and fixed with
// `bun run format`), which is also an order of magnitude faster.
// ─────────────────────────────────────────────────────────────────────────
import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unusedImports from "eslint-plugin-unused-imports";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "scripts/codemod-*.mjs",
      // Auto-generated by the @lovable.dev/mcp-js Vite plugin and rewritten on
      // every build. Its banner says "do not edit", so its seven no-var
      // findings were unfixable by design and permanently red.
      "supabase/functions/mcp/index.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx,js,jsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      "simple-import-sort": simpleImportSort,
      "unused-imports": unusedImports,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],

      // `@typescript-eslint/no-unused-vars` is OFF on purpose: it and
      // `unused-imports/no-unused-vars` detect the same thing, so every
      // finding was reported twice (516 duplicated messages).
      "@typescript-eslint/no-unused-vars": "off",
      // An unused *import* is always safe to delete and is auto-fixable, so
      // it stays an error. Unused *variables* are budgeted below.
      "unused-imports/no-unused-imports": "error",

      // Consistent import/export ordering. Warn (not error) because
      // reordering side-effect imports can change CSS cascade order, so it
      // must never be auto-fixed blindly in a pre-commit hook.
      "simple-import-sort/imports": "warn",
      "simple-import-sort/exports": "warn",

      // ─────────────────────────────────────────────────────────────────
      // Tracked debt: reported, budgeted, not yet fixed.
      //
      // These were "error" while nothing enforced the lint gate, which meant
      // 635 errors accumulated and `bun run lint` was permanently red. A gate
      // that never passes gates nothing, so the choice was between deleting
      // the rules (losing the signal) or admitting the backlog and freezing
      // it. This is the second option.
      //
      // Every rule below stays ON and keeps reporting. It is demoted to
      // "warn" only so `bun run lint` can exit 0 on a clean-of-new-errors
      // tree, and `bun run lint:budget` fails the build if any of these
      // counts goes UP. See scripts/lint-budget.mjs and lint-budget.json.
      //
      // Fixing them properly means real work per call site, not a codemod:
      //
      //   react-hooks/refs (188), set-state-in-effect (99), purity (24),
      //   immutability (19), static-components (15),
      //   preserve-manual-memoization (5), use-memo (1)
      //     The React Compiler rule family from eslint-plugin-react-hooks v7.
      //     Reading a ref during render and setting state inside an effect are
      //     genuine cascading-render hazards and the main blocker for React 19
      //     / the compiler. Each needs the surrounding component understood.
      //
      //   @typescript-eslint/no-explicit-any (201)
      //     Mostly Supabase results where the generated types in
      //     src/integrations/supabase/types.ts are behind the schema.
      //     Regenerating those types removes a large share in one pass.
      //
      //   unused-imports/no-unused-vars (69)
      //     Dead declarations left by feature removals, e.g. the
      //     prayer-logging state still sitting in PrayerTimes.tsx. Deleting
      //     them is a per-file judgement about whether the feature is coming
      //     back, so they are listed rather than mass-deleted.
      //
      //   @typescript-eslint/ban-ts-comment (14)
      //     14 files open with @ts-nocheck, so they are excluded from
      //     typechecking entirely. Worth knowing when reading "typecheck
      //     clean": it is clean over everything that is actually checked.
      //     Most cite the same stale-generated-types cause as the anys.
      // ─────────────────────────────────────────────────────────────────
      "react-hooks/refs": "warn",
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/static-components": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/use-memo": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/ban-ts-comment": "warn",
    },
  },
  // Ensure prettier config disables formatting conflicts
  eslintConfigPrettier,
  // Node globals for build / config / supabase edge function files.
  {
    files: [
      "*.config.{js,ts,cjs,mjs}",
      "playwright-fixture.ts",
      "supabase/functions/**/*.ts",
    ],
    languageOptions: {
      globals: { ...globals.node, Deno: "readonly" },
    },
  },
);
