/**
 * The dotted world map's data.
 *
 * Generated by `scripts/travel/build-dot-grid.mjs` into
 * `public/data/world-dots.json` (~72 kB, ~22 kB gzipped). It is fetched, not
 * imported, so it stays out of every JavaScript chunk and is cached by the
 * browser like any other asset — the stamp map is one screen, and nobody who
 * never opens it should pay for 178 countries' worth of dots.
 */

export interface DotCountry {
  iso: string;
  /** Arabic name, from Natural Earth's own NAME_AR field. */
  ar: string;
  en: string;
  /** Continent, already in Arabic. */
  cont: string;
  /** Label anchor: the centroid of this country's dots, so it sits on land. */
  at: [col: number, row: number];
  dots: [col: number, row: number][];
}

export interface WorldDots {
  /** Grid spacing in degrees. */
  step: number;
  cols: number;
  rows: number;
  minLat: number;
  maxLat: number;
  countries: DotCountry[];
}

const ASSET_URL = '/data/world-dots.json';

let cache: Promise<WorldDots> | null = null;

/** Loaded at most once per session. */
export function loadWorldDots(): Promise<WorldDots> {
  cache ??= fetch(ASSET_URL)
    .then(async (response) => {
      if (!response.ok) throw new Error(`world_dots_${response.status}`);
      return (await response.json()) as WorldDots;
    })
    .catch((error: unknown) => {
      // Allow a later retry rather than caching the failure forever.
      cache = null;
      throw error;
    });
  return cache;
}

/** `{ "SA": DotCountry }` for O(1) lookup from a stamp row. */
export function indexByIso(world: WorldDots): Map<string, DotCountry> {
  return new Map(world.countries.map((country) => [country.iso, country]));
}

/**
 * `cell key → iso` so a tap on the canvas resolves to a country in constant
 * time. Hit-testing 6,800 dots by distance on every pointer move would be the
 * only slow thing on the screen.
 */
export function buildCellIndex(world: WorldDots): Map<number, string> {
  const index = new Map<number, string>();
  for (const country of world.countries) {
    for (const [col, row] of country.dots) {
      index.set(row * world.cols + col, country.iso);
    }
  }
  return index;
}
