import { expect, test } from './fixtures';

/**
 * PWA surface. These are the parts a unit test cannot reach because they only
 * exist in the built output: the manifest as served, and the app-shell service
 * worker generated by the Vite plugin in writeBundle.
 */
test.describe('pwa', () => {
  test('serves a valid manifest with the shortcuts and icons it declares', async ({
    request,
  }) => {
    const res = await request.get('/manifest.json');
    expect(res.status()).toBe(200);

    const manifest = (await res.json()) as {
      name: string;
      start_url: string;
      display: string;
      dir: string;
      lang: string;
      theme_color: string;
      shortcuts?: Array<{ name: string; url: string }>;
      icons: Array<{ src: string; sizes: string; purpose?: string }>;
    };

    expect(manifest.start_url).toBe('/');
    expect(manifest.display).toBe('standalone');
    expect(manifest.dir).toBe('rtl');
    expect(manifest.lang).toBe('ar');

    // theme_color has to match the theme the app actually boots into. The
    // default resolves to 'light' in both AppContext and the index.html FOUC
    // guard, so a dark value here would flash on launch.
    expect(manifest.theme_color).toBe('#f1f0f4');

    // Installability needs a maskable icon; Chrome warns without one.
    expect(manifest.icons.some((i) => i.purpose === 'maskable')).toBe(true);

    expect(manifest.shortcuts?.length ?? 0).toBeGreaterThanOrEqual(1);

    // Every asset the manifest promises must actually be served, and every
    // shortcut must point at a route that resolves.
    for (const icon of manifest.icons) {
      const iconRes = await request.get(icon.src);
      expect(iconRes.status(), `${icon.src} is referenced but not served`).toBe(200);
    }
    for (const shortcut of manifest.shortcuts ?? []) {
      const routeRes = await request.get(shortcut.url);
      expect(routeRes.status(), `${shortcut.url} does not resolve`).toBe(200);
    }
  });

  test('index.html declares theme-color for both colour schemes', async ({ page }) => {
    await page.goto('/');
    const light = page.locator('meta[name="theme-color"][media*="light"]');
    const dark = page.locator('meta[name="theme-color"][media*="dark"]');
    await expect(light).toHaveAttribute('content', '#f1f0f4');
    await expect(dark).toHaveAttribute('content', '#1c1827');
  });

  test('the generated service worker is served and carries a precache manifest', async ({
    request,
  }) => {
    const res = await request.get('/sw.js');
    expect(res.status()).toBe(200);
    const body = await res.text();

    // Emitted by build/appShellServiceWorker.ts. If the plugin ever stops
    // running, the app keeps advertising offline support without having it.
    expect(body).toContain('PRECACHE');
    expect(body, 'template placeholders were not substituted').not.toContain('__SW_');
    // The shell itself plus at least one fingerprinted asset.
    expect(body).toContain('/index.html');
    expect(body).toMatch(/\/assets\/[^"']+\.js/);
  });

  test('registers the service worker at runtime', async ({ page }) => {
    await page.goto('/');
    const registered = await page
      .waitForFunction(
        async () => {
          const reg = await navigator.serviceWorker?.getRegistration('/');
          return !!reg;
        },
        undefined,
        { timeout: 15_000 },
      )
      .then(() => true)
      .catch(() => false);

    expect(registered, 'no service worker registration for scope /').toBe(true);
  });

  test('the diwan corpus is served as a JSON asset, not bundled JavaScript', async ({
    request,
  }) => {
    // Regression guard: this corpus used to be an 18,876-line TypeScript array
    // that Rollup hoisted into a 349 kB gzipped chunk loaded by every /diwan
    // route. It must stay a fetched asset.
    const res = await request.get('/data/diwan-poetry.json');
    expect(res.status()).toBe(200);
    expect(res.headers()['content-type']).toContain('json');

    const eras = (await res.json()) as Array<{ id: string; poets: unknown[] }>;
    expect(Array.isArray(eras)).toBe(true);
    expect(eras.length).toBeGreaterThanOrEqual(6);
    expect(eras.some((e) => e.id === 'jahili')).toBe(true);
  });
});
