import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { FitnessActivity, GeoCoordinate } from '../utils/validation/schemas';
import { haversineDistance } from '../utils/helpers/math';
export interface FitnessState { activities: FitnessActivity[]; currentActivity: FitnessActivity | null; isTracking: boolean; totalDistance: number; }
export interface FitnessActions { startActivity: (type: FitnessActivity['type'], userId: string) => void; stopActivity: () => void; addCoordinate: (coord: GeoCoordinate) => void; clearHistory: () => void; }
const initialFitnessState: FitnessState = { activities: [], currentActivity: null, isTracking: false, totalDistance: 0 };
export const useFitnessStore = create<FitnessState & FitnessActions>()(
  persist((set, get) => ({ ...initialFitnessState, startActivity: (type, userId) => set({ isTracking: true, currentActivity: { id: crypto.randomUUID(), user_id: userId, type, start_time: new Date().toISOString(), distance_meters: 0, duration_seconds: 0, route_coordinates: [] } }), stopActivity: () => set((state) => { if (!state.currentActivity) return state; const completedActivity: FitnessActivity = { ...state.currentActivity, end_time: new Date().toISOString(), duration_seconds: Math.floor((new Date().getTime() - new Date(state.currentActivity.start_time).getTime()) / 1000) }; return { isTracking: false, currentActivity: null, activities: [...state.activities, completedActivity], totalDistance: state.totalDistance + completedActivity.distance_meters }; }), addCoordinate: (coord) => set((state) => { if (!state.currentActivity || !state.isTracking) return state; const lastCoord = state.currentActivity.route_coordinates.length > 0 ? state.currentActivity.route_coordinates[state.currentActivity.route_coordinates.length - 1] : null; let addedDistance = 0; if (lastCoord) { addedDistance = haversineDistance(lastCoord.lat, lastCoord.lng, coord.lat, coord.lng); const timeDiffSec = (new Date(coord.timestamp || new Date().toISOString()).getTime() - new Date(lastCoord.timestamp || new Date().toISOString()).getTime()) / 1000; const speed = timeDiffSec > 0 ? addedDistance / timeDiffSec : 0; if (addedDistance < 1 || speed > 15) { return state; } } return { currentActivity: { ...state.currentActivity, distance_meters: state.currentActivity.distance_meters + addedDistance, route_coordinates: [...state.currentActivity.route_coordinates, coord] } }; }), clearHistory: () => set({ activities: [], totalDistance: 0 }) }),
  { name: 'zen-elite-fitness-store', storage: createJSONStorage(() => localStorage) })
);
